# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/Suchet Gopal/Desktop/cmod_project/hdl/cmod_a7.xdc

# Block Designs: bd/block_design/block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_clk_wiz_0_0_1/block_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_clk_wiz_0_0 || ORIG_REF_NAME==block_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_czt_spi_core_0_0_1/block_design_czt_spi_core_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==block_design_czt_spi_core_0_0 || ORIG_REF_NAME==block_design_czt_spi_core_0_0} -quiet] -quiet

# XDC: c:/Users/Suchet Gopal/Desktop/cmod_project/scripts/project/cmod_a7.gen/sources_1/bd/block_design/block_design_ooc.xdc
